
// Copyright (c) 2018 Alibaba Inc. All Rights Reserved.
//
/// \file errno.h
/// \author Shi Yudi <fufeng.syd@alipay.com>
/// \date 2018-04-28
///

// DO NOT EDIT. This file is automatically generated from ob_errno.def.
// DO NOT EDIT. This file is automatically generated from ob_errno.def.
// DO NOT EDIT. This file is automatically generated from ob_errno.def.
// To add errno in this header file, you should use DEFINE_***_DEP to define errno in ob_errno.def
// For any question, call fyy280124
#ifndef __OBERROR_LIB_OB_ERROR_H__
#define __OBERROR_LIB_OB_ERROR_H__


constexpr int OB_MAX_SAME_ERRORCODE                  = 5;
constexpr int OB_MAX_ERROR_CODE                      = 65535;

constexpr int OB_MAX_RAISE_APPLICATION_ERROR         = -20000;
constexpr int OB_MIN_RAISE_APPLICATION_ERROR         = -20999;


#endif /* __OBERROR_LIB_OB_ERROR_H__ */
